// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CardTier struct {
	ID      string `json:"id"`
	Card    string `json:"card"`
	Class   string `json:"class"`
	Act1    int    `json:"act1"`
	Act2    int    `json:"act2"`
	Act3    int    `json:"act3"`
	Overall int    `json:"overall"`
	Upgrade int    `json:"upgrade"`
}

type NewCardTier struct {
	Card    string `json:"card"`
	Class   string `json:"class"`
	Act1    int    `json:"act1"`
	Act2    int    `json:"act2"`
	Act3    int    `json:"act3"`
	Overall int    `json:"overall"`
	Upgrade int    `json:"upgrade"`
}
